flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git+ssh://git@github.com/werner/persistent-audit.git
    commit: 42fe3878946492e28703847a919355b11268bb82
  extra-dep: true
extra-deps:
- persistent-mongoDB-2.6.0
- persistent-parser-0.1.0.2
resolver: lts-8.9
